# Generated by Django 5.2.3 on 2025-06-28 17:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("MONTHLY_SALES", "Oylik Sotuvlar"),
                            ("INVENTORY_TURNOVER", "Inventar Aylanmasi"),
                            ("SUPPLIER_PERFORMANCE", "Yetkazib Beruvchi Samaradorligi"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Kutilmoqda"),
                            ("GENERATING", "Yaratilmoqda"),
                            ("COMPLETED", "Yakunlandi"),
                            ("FAILED", "Xatolik"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("requested_by_id", models.CharField(max_length=255)),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text="e.g., {'start_date': '2025-01-01', 'end_date': '2025-01-31'}",
                    ),
                ),
                (
                    "file_path",
                    models.FileField(blank=True, null=True, upload_to="reports/"),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
