# Generated by Django 5.2.3 on 2025-06-28 17:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name for the template",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "subject_template",
                    models.CharField(
                        help_text="Subject template, e.g., 'Welcome, {username}!'",
                        max_length=255,
                    ),
                ),
                (
                    "body_template",
                    models.TextField(
                        help_text="Body template with placeholders, e.g., 'Your order {order_id} has been shipped.'"
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recipient", models.CharField(max_length=255)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Elektron Pochta"),
                            ("SMS", "SMS Xabar"),
                            ("IN_APP", "Ilova Ichida"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Kutilmoqda"),
                            ("SENT", "Yuborildi"),
                            ("FAILED", "Xatolik"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("sent_content", models.TextField()),
                ("error_message", models.TextField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "template_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="notifications.notificationtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
