# Generated by Django 5.2.3 on 2025-06-28 17:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "actor_id",
                    models.CharField(
                        help_text="ID of the user who performed the action",
                        max_length=255,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Yaratish"),
                            ("UPDATE", "Yangilash"),
                            ("DELETE", "Ochirish"),
                            ("LOGIN", "Tizimga kirish"),
                            ("EXECUTE", "Bajarish"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "target_model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("target_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "details",
                    models.JSONField(
                        default=dict,
                        help_text="e.g., {'old_status': 'pending', 'new_status': 'shipped'}",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
