# Generated by Django 5.2.3 on 2025-06-28 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carrier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("GROUND", "Yer orqali"),
                            ("AIR", "Havo orqali"),
                            ("SEA", "Dengiz orqali"),
                            ("RAIL", "Temir yo'l orqali"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "tracking_url_template",
                    models.URLField(
                        blank=True,
                        help_text="e.g., https://carrier.com/track?id={tracking_number}",
                        max_length=512,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Carriers",
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_order_id",
                    models.UUIDField(help_text="ID of the order from Order Service"),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("LABEL_CREATED", "Label Yaratildi"),
                            ("IN_TRANSIT", "Yo'lda"),
                            ("OUT_FOR_DELIVERY", "Yetkazish uchun chiqdi"),
                            ("DELIVERED", "Yetkazib Berildi"),
                            ("FAILED_ATTEMPT", "Muvaffaqiyatsiz Urinish"),
                            ("EXCEPTION", "Istisno Holat"),
                        ],
                        default="LABEL_CREATED",
                        max_length=50,
                    ),
                ),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("estimated_delivery_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "carrier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipments",
                        to="logistics.carrier",
                    ),
                ),
            ],
        ),
    ]
